name: Deb package for Ubuntu Bionic

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:
    inputs:
      base_version:
        description: 'Base Version'
        required: true
        default: "0.44"

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install build dependencies
      run: sudo apt-get install -y build-essential libssl-dev debhelper
      
    - name: Make Deb Package
      run: dch -v "${{ inputs.base_version }}.${{ github.run_number }}" "Ubuntu package build" && dpkg-buildpackage -rfakeroot --no-sign && mv ../peervpn*.deb .

    - name: Upload resulting deb package
      uses: actions/upload-artifact@v3
      with:
        name: peervpn_bionic_amd64_${{ inputs.base_version }}.${{ github.run_number }}.deb
        path: peervpn*.deb

    - name: Install deb package
      run: mkdir deployment && mv ./peervpn*.deb ./deployment && sudo dpkg -i -R ./deployment

    - name: Verify binary existence at /usr/local/bin/peervpn
      run: ls -la /usr/local/bin/peervpn
