name: Deb package for Ubuntu Bionic

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:
    inputs:
      base_version:
        description: 'Base Version'
        required: true
        default: "0.44"

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install build dependencies
      run: sudo apt-get install -y build-essential libssl-dev debhelper devscripts dpkg-dev
      
    - name: Make Deb Package
      run: dch -v "${{ inputs.base_version }}.${{ github.run_number }}" "Ubuntu package build" && dpkg-buildpackage -rfakeroot --no-sign && mkdir -p ./apt/dists/bionic/main/binary-amd64 && mv ../peervpn*.deb ./apt/dists/bionic/main/binary-amd64

    - name: Upload resulting deb package
      uses: actions/upload-artifact@v3
      with:
        name: peervpn_bionic_amd64_${{ inputs.base_version }}.${{ github.run_number }}.deb.zip
        path: apt/dists/bionic/main/binary-amd64/peervpn*.deb

    - name: Create custom apt repo
      run:  cd ./apt && dpkg-scanpackages dists/bionic/main/binary-amd64 > ./dists/bionic/main/binary-amd64/Packages

    - name: Expose custom apt repo over http and pull package
      run:  |
        echo "deb [trusted=yes] http://127.0.0.1/apt bionic main" > ./peervpn.list && sudo cp ./peervpn.list /etc/apt/sources.list.d
        sudo python3 -m http.server 80 &
        sudo apt-get update && sudo apt-get install -y peervpn

    - name: Verify binary existence at /usr/local/bin/peervpn
      run: ls -la /usr/local/bin/peervpn
