name: Deb package for Ubuntu Bionic

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get install -y build-essential libssl-dev debhelper
      
    - name: Make Deb Package
      run: dpkg-buildpackage -rfakeroot && pwd && ls -la && ls -la ..

    - name: Look around
      run: pwd && ls -la && ls -la ..

    - name: Upload resulting deb package
      uses: actions/upload-artifact@v3
      with:
        name: PeerVPN-UbuntuBionic.deb
        path: output/test/code-coverage.html
