name: Deb package for Ubuntu Bionic

on:
  push:
    branches: [ $default-branch ]
  workflow_dispatch:
    inputs:
      base_version:
        description: 'Base Version'
        required: true
        default: "0.44"

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Install build dependencies
      run: sudo apt-get install -y build-essential libssl-dev debhelper devscripts dpkg-dev
      
    - name: Make Deb Package
      run: dch -v "${{ inputs.base_version }}.${{ github.run_number }}" "Ubuntu package build" && dpkg-buildpackage -rfakeroot --no-sign && mkdir -p deployment/contrib && mv ../peervpn*.deb ./deployment/contrib

    - name: Upload resulting deb package
      uses: actions/upload-artifact@v3
      with:
        name: peervpn_bionic_amd64_${{ inputs.base_version }}.${{ github.run_number }}.deb
        path: deployment/contrib/peervpn*.deb

    - name: Create custom apt repo
      run:  dpkg-scanpackages ./deployment > ./deployment/Packages && gzip ./deployment/Packages

    - name: Expose custom apt repo over http
      run:  sudo python -m http.server 80 --directory ./deployment/ &

    - name: Add custom apt repo to local apt sources
      run:  sudo echo "deb [trusted=yes] http://127.0.0.1 contrib" > /etc/apt/sources.list.d/peervpn.list

    - name: Install deb package
      run:  sudo apt-get update && sudo apt-get install -y peervpn

    - name: Verify binary existence at /usr/local/bin/peervpn
      run: ls -la /usr/local/bin/peervpn
